[package]
name = "RollingOHLC"
version = "0.1.0"
edition = "2021"
authors = ["Shantanu"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[example]]
name = "a"
path = "examples/a.rs"